export const names = {
  dashboard: 'Dashboard',
  add_product: 'Add Product',
  product_name: 'Product Name',
  jira_url: 'Jira URL',
  username: 'Username',
  api_key: 'API Key',
  product_manager: 'Product Manager',
  close: 'Close',
  add: 'Add',
  products: 'Products',
  last_updated: 'Last updated',
  report_dashboard: 'Reports Dashboard',
  defects_injected: 'Defects Injected',
  defects_fixed: 'Defects Fixed',
  defects_open: 'Defects Open',
  committed: 'Committed',
  story_points: 'Story Points',
  velocity: 'Velocity',
  effort_variance: 'Effort Variance',
  hours: 'Hours',
  completed: 'Completed',
  estimated: 'Estimated',
  actual: 'Actual',
  defects_injection_rate: 'Defect Injection Rate',
  number_of_defects: 'Number of Defects',
  defect_count: 'Defect Count',
  time_bugs_chart_name: 'Time Spent On Bugs Vs Stories',
  bugs: 'Bugs',
  stories: 'Stories',
  defects_trend: 'Defects Trend',
  total_defects: 'Total Defects',
  defects_injected_sprint: 'Defects Injected (Sprint)',
  story_defects_injected: 'Story Defects Injected (Sprint)',
  defects_count: 'Defects Count',
  trend_across_sprints: 'Trend Across Sprints',
  completed_outside_sprint: 'Completed outside sprint',
  not_completed: 'Not completed',
  punted: 'Punted',
  tickets_count: 'Tickets Count',
  add_project: 'Add Project',
  project_name: 'Project Name',
  yes: 'Yes',
  no: 'No',
};

export const placeholder = {
  product_name: 'e.g. VaticaHealth',
  jira_url: 'e.g. htpps://productname.atlassian.net',
  username: 'Enter Username here',
  api_key: 'Enter API Key here',
  product_manager: 'e.g. Summet Mehta',
  sprint_dropdown: 'Selected Most Recent Six Sprints of All',
  project_name: 'e.g. VaticaHealth',
};

export const text = {
  search_for_product: 'Search for Product',
  sprint_duration: 'Sprint Duration',
  sync_successfull: 'Synced Successfully',
  login_with_google: 'Login with Google',
  logout_caption: 'Do you really want to logout?',
  product_is_syncing: 'Product is Syncing',
  no_data_found: 'Sorry, No Data Found',
  no_product_found: 'Sorry, No Products Found',
  changes_lost_caption: 'All the changes will be lost. Do you want to proceed?',
};

export const error = {
  something_went_wrong: 'Something went wrong!',
  auth: 'Error in authenticating user',
  data: 'Error in fetching data',
  fetchProducts: 'Error in fetching Products',
  addProduct: 'Error in adding product',
  addProject: 'Error in adding project',
  syncProdut: 'Error in syncing product',
  fetchReport: 'Error in fetching Product Report',
  fetchProductSprint: 'Error in fetching Product Sprints',
};

export const priorities = {
  highest: 'Highest',
  blocker: 'Blocker',
  p1: 'P1',
  high: 'High',
  critical: 'Critical',
  p2: 'P2',
  medium: 'Medium',
  major: 'Major',
  p3: 'P3',
  low: 'Low',
  minor: 'Minor',
  p4: 'P4',
  lowest: 'Lowest',
  trivial: 'Trivial',
  p5: 'P5',
  p6: 'P6',
  none: 'None',
};
